[color]
  ui = true
[core]
  excludesfile = /Users/anhtran/.gitignore_global
  editor       = vim
[user]
  name  = anhtrantuan
  email = anhtrantuan.hcmc@gmail.com
[push]
  default = simple
[alias]
  aa = add -A
  ap = add -p
  co = checkout
  cm = commit
  cp = cherry-pick
  cs = commit -s
  p  = push
  pf = push -f
  pp = push -f production HEAD:master
  ps = push -f staging HEAD:master
  pu = pull
  pua = pull --all
  ss = status
